apiVersion: fission.io/v1
kind: MessageQueueTrigger
metadata:
  creationTimestamp: null
  name: k2k
  namespace: kafka-keda-k2k-go
spec:
  contentType: application/json
  cooldownPeriod: 30
  respTopic: response-topic
  topic: request-topic
  errorTopic: error-topic
  functionref:
    functionweights: null
    name: k-consumer
    type: name
  maxReplicaCount: 100
  maxRetries: 3
  messageQueueType: kafka
  metadata:
    bootstrapServers: my-cluster-kafka-0.my-cluster-kafka-brokers.infra.svc:9092
    consumerGroup: my-group
    topic: request-topic
  minReplicaCount: 0
  mqtkind: keda
  pollingInterval: 5